### ISSUE TITLE
apify push override current version in app

### ISSUE THREAD

**Issue by drobnikj** [apify/apify-cli#128] opened 2019-09-23 13:37 UTC
Actually, one more thing. When a user pushes the actor to Apify using CLI, then modifies it there manually, and then pushes it again, all changes there will be lost, without any warning. I think it will bite someone eventually - imagine how angry you'd be to lose a lot of your work. 

One simple way to deal with this would be to add some flag to actor version indicating how it was last modified (UI, API, ...) and if it's "UI", then just ask the user for a confirmation (which can be overridden using `--force-overwrite` flag).

_Originally posted by @jancurn in https://github.com/apifytech/apify-cli/pull/127#issuecomment-533820836_

We need to create flag in-app, from where we did the last update. Then use it in CLI.

**Comment by B4nan** [comment] 2024-03-11 14:07
Closing as a duplicate of #370, resolved via #506

**Closed by B4nan** 2024-03-11 14:07 UTC
Labels: enhancement, t-platform
